name: V2ray Heroku Docker Image

on: 
  push:
  schedule:
    - cron: "0 0 * * 5"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        export buildTime=$(date +%s)
        docker build . --file Dockerfile --tag v2heroku:$GITHUB_SHA
    
  run:

    needs: build

    env:
      AppName: test
    
    steps:
    - name: Run the Docker image
      run: |
        export AppName=test
        docker run --name=run_test v2heroku:$GITHUB_SHA bash
