name: V2ray Heroku Docker Image

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:V2Heroku-$(date +%s)
    
    - name: Run the Docker image
      run: |
        export AppName=test
        docker run