name: V2ray Heroku Docker Image

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        export buildTime=$(date +%s)
        docker build . --file Dockerfile --tag v2Heroku:$buildTime
    
    - name: Run the Docker image
      run: |
        export AppName=test
        docker run v2Heroku:$buildTime